"""Added intrusion table

Revision ID: 031376c29698
Revises: d58dbfeca6fc
Create Date: 2018-03-15 13:03:22.986205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '031376c29698'
down_revision = 'd58dbfeca6fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intrusion_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provided_user', sa.String(length=120), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intrusion_attempt_timestamp'), 'intrusion_attempt', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intrusion_attempt_timestamp'), table_name='intrusion_attempt')
    op.drop_table('intrusion_attempt')
    # ### end Alembic commands ###
