"""Added Drones table and few relationships

Revision ID: 06f7da4e2785
Revises: 031376c29698
Create Date: 2018-03-17 13:43:35.655361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06f7da4e2785'
down_revision = '031376c29698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('url', sa.String(length=100), nullable=False),
    sa.Column('controller', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['controller'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drones_controller'), 'drones', ['controller'], unique=False)
    op.create_index(op.f('ix_drones_name'), 'drones', ['name'], unique=True)
    op.create_index(op.f('ix_drones_url'), 'drones', ['url'], unique=True)
    op.create_index(op.f('ix_action_logs_action_id'), 'action_logs', ['action_id'], unique=False)
    op.create_index(op.f('ix_action_logs_timestamp'), 'action_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_intrusion_attempt_timestamp'), 'intrusion_attempt', ['timestamp'], unique=False)
    op.create_index(op.f('ix_login_logs_timestamp'), 'login_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_surname'), 'user', ['surname'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_surname'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_login_logs_timestamp'), table_name='login_logs')
    op.drop_index(op.f('ix_intrusion_attempt_timestamp'), table_name='intrusion_attempt')
    op.drop_index(op.f('ix_action_logs_timestamp'), table_name='action_logs')
    op.drop_index(op.f('ix_action_logs_action_id'), table_name='action_logs')
    op.drop_index(op.f('ix_drones_url'), table_name='drones')
    op.drop_index(op.f('ix_drones_name'), table_name='drones')
    op.drop_index(op.f('ix_drones_controller'), table_name='drones')
    op.drop_table('drones')
    # ### end Alembic commands ###
