"""actionlogs primkeyworkaround

Revision ID: 55daf769c180
Revises: daec06696f32
Create Date: 2018-06-02 21:11:00.357940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55daf769c180'
down_revision = 'daec06696f32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('action')
    op.drop_index('ix_action_logs_action_id', table_name='action_logs')
    op.drop_index('ix_action_logs_timestamp', table_name='action_logs')
    op.drop_table('action_logs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('action_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['action.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_action_logs_timestamp', 'action_logs', ['timestamp'], unique=False)
    op.create_index('ix_action_logs_action_id', 'action_logs', ['action_id'], unique=False)
    op.create_table('action',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
