"""Drone mods to allow multiple ports for control and video

Revision ID: daec06696f32
Revises: 06f7da4e2785
Create Date: 2018-03-30 13:39:37.468939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daec06696f32'
down_revision = '06f7da4e2785'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drones', sa.Column('control_port', sa.Integer(), nullable=True))
    op.add_column('drones', sa.Column('video_port', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drones', 'video_port')
    op.drop_column('drones', 'control_port')
    # ### end Alembic commands ###
